title: Jacob Hoover, MSc
logo: assets/Jacob-Hoover-prof-pic.jpg
description: Omics | Data Science | Applied ML/AI | Structural Biology | Drug Discovery
show_downloads: true
theme: jekyll-theme-minimal
