title: Vivek Das PhD, MSc
logo: /assets/vd.jpeg
description: Omics in Clinical Trials | Computational Systems Biology | Data Science I Applied ML/AI | Strategy & Innovation | Mentor | Thought Leader | Scientific Advisory Board Member
#show_downloads: true
theme: jekyll-theme-minimal
